name: papersnap
description: "Capture, organize, and transform your physical documents into pristine digital files with this intuitive app, offering smart auto-detection, multi-page scanning, and the flexibility to save as high-quality PDFs or individual images."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  camera: ^0.11.2
  image: ^4.0.0
  path_provider: ^2.0.0
  pdf: ^3.0.0
  shared_preferences: ^2.0.0
  permission_handler: ^12.0.0
  printing: ^5.0.0
  local_auth: ^2.0.0
  share_plus: ^11.0.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "icons_to_use/android/play_store_512.png"

flutter:
  uses-material-design: true
